2019-11-19T17:16:08|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\MFCS_python_old\Camera&PumpApp.py", line 181, in <module>
    app = HamamatsuApp(sys.argv)
  File "C:\Users\Admin\Desktop\MFCS_python_old\Camera&PumpApp.py", line 24, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\Users\Admin\Desktop\MFCS_python_old\Camera&PumpApp.py", line 140, in setup
    self.add_hardware(MFCSHardware(self))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 80, in __init__
    self.setup()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 29, in setup
    self.add_operation("set zero pressure",setall_zeropressure)
NameError: name 'setall_zeropressure' is not defined

