2019-11-19T17:20:52|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\MFCS_python_old\Camera&PumpApp.py", line 181, in <module>
    app = HamamatsuApp(sys.argv)
  File "C:\Users\Admin\Desktop\MFCS_python_old\Camera&PumpApp.py", line 24, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\Users\Admin\Desktop\MFCS_python_old\Camera&PumpApp.py", line 140, in setup
    self.add_hardware(MFCSHardware(self))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 80, in __init__
    self.setup()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 29, in setup
    self.add_operation("set zero pressure", MFCSDevice.setall_zeropressure(self))
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpDevice.py", line 85, in setall_zeropressure
    error = lib_mfcs.mfcs_set_auto(c_ulonglong(self.mfcsHandle),0,c_float(0))
AttributeError: 'MFCSHardware' object has no attribute 'mfcsHandle'

