2019-11-11T14:59:37|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 40, in connect
    self.set_pressure_1.hardware_set_func = self.MFCS.set_pressure_channel(1)
TypeError: set_pressure_channel() missing 1 required positional argument: 'ch'

2019-11-11T14:59:38|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 40, in connect
    self.set_pressure_1.hardware_set_func = self.MFCS.set_pressure_channel(1)
TypeError: set_pressure_channel() missing 1 required positional argument: 'ch'

