2019-11-11T14:53:40|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 41, in connect
    self.read_pressure_2.hardware_read_func = self.MFCS.read_preessure_channel
AttributeError: 'MFCSDevice' object has no attribute 'read_preessure_channel'

2019-11-11T14:53:41|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 41, in connect
    self.read_pressure_2.hardware_read_func = self.MFCS.read_preessure_channel
AttributeError: 'MFCSDevice' object has no attribute 'read_preessure_channel'

2019-11-11T14:53:43|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 41, in connect
    self.read_pressure_2.hardware_read_func = self.MFCS.read_preessure_channel
AttributeError: 'MFCSDevice' object has no attribute 'read_preessure_channel'

2019-11-11T14:53:44|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 41, in connect
    self.read_pressure_2.hardware_read_func = self.MFCS.read_preessure_channel
AttributeError: 'MFCSDevice' object has no attribute 'read_preessure_channel'

